import pytest
import convert_to_gerund

@pytest.mark.parametrize("input,expected", [
    ("run",     "running"), 
    ("sit",     "sitting"),
    ("die",     "dying"),
    ("lie",     "lying"),
    ("tie",     "tying"),
    ("avoid",   "avoiding"),
    ("fight",   "fighting"),
    ("finish",  "finishing"),
    ("go",      "going"),
    ("hear",    "hearing"),
    ("jump",    "jumping"),
    ("keep",    "keeping"),
    ("mention", "mentioning"),
    ("mind",    "minding"),
    ("miss",    "missing"),
    ("prevent", "preventing"),
    ("risk",    "risking"),
    ("sing",    "singing"),
    ("sleep",   "sleeping"),
    ("start",   "starting"),
    ("suggest",	"suggesting"),
    ("treat",	"treating"),
    ("work",	"working"),
    ("bake",    "baking"),
    ("change",	"changing"),
    ("fake",	"faking"),
    ("have",	"having"),
    ("live",	"living"),
    ("make",	"making"),
    ("shake",	"shaking"),
    ("smile",	"smiling"),
    ("take",	"taking"),
    ("write",	"writing"),
    ("agree",   "agreeing"),
    ("dye",	    "dyeing"),
    ("free",    "freeing"),
    ("see",	    "seeing"),
    ("tiptoe",  "tiptoeing"),
    ("admit",   "admitting"),
    ("commit",	"committing"),
    ("get",	    "getting"),
    ("plan",	"planning"),
    ("put",	    "putting"),
    ("refer",	"referring"),
    ("enjoy",	"enjoying"),
    ("enter",	"entering"),
    ("fix",	    "fixing"),
    ("happen",	"happening"),
    ("offer",	"offering"),
    ("snow",	"snowing"),
    ("suffer",	"suffering"),
    ("visit",	"visiting"),
    
])
def test_transformToIngForm(input, expected):
    result = convert_to_gerund.transformVerbToIngForm(input)
    assert result == expected
